name: CI

on:
  push:
    branches:
      - "**"
      - "!master"
  pull_request:
    branches:
      - "**"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "16.x"
          - "18.x" # whichever node versions you support
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - run: pnpm lint && pnpm build
